#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Init antigen"
curl -L git.io/antigen > antigen.zsh
source antigen.zsh
