#!/bin/bash

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd "$HOME"

echo "Setup nvim for git"
git config --global core.editor "nvim"

echo "Install brew"
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

sudo sh ~/.osx

# Recover from Brewfile
## eg: brew bundle dump -> Create Brewfile
## brew bundle -> Recover it
brew bundle

# install additional
sh ~/brew.sh
sh ~/npm.sh

# intall simple menubar
# git clone https://github.com/izifortune/simple-bar.git $HOME/Library/Application\ Support/Übersicht/widgets/simple-bar
# wal colors alacritty
git clone https://github.com/egeesin/alacritty-color-export $HOME/code/alacritty-color-export
chmod +x $HOME/code/alacritty-color-export/script.sh
./$HOME/code/alacritty-color-export/script.sh
