#!/usr/bin/env sh
source ~/.cache/wal/colors.sh

##Passive colors
#p1="${color8:1}"

##active colors - (same as position on bar)
#c1="${color2:1}"
#c2="${color4:1}"
#c3="${color3:1}"
#c4="${color9:1}"
#c5="${color5:1}"
CBACK=$(echo $background | sed 's/#//')
CFORE=$(echo $foreground | sed 's/#//')
CACTV=$(echo $color3 | sed 's/#//')
CNORM=$(echo $color1 | sed 's/#//')
CINSE=$(echo $foreground | sed 's/#//')

yabai -m config status_bar                   on
yabai -m config status_bar_background_color  0xff$CBACK
yabai -m config status_bar_foreground_color  0xff$CFORE

yabai -m config window_border                off
yabai -m config window_border_width          10
yabai -m config active_window_border_color   0xff$CACTV
yabai -m config normal_window_border_color   0xff$CNORM
yabai -m config insert_window_border_color   0xff$CINSE

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autoraise
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                off
yabai -m config active_window_opacity        0.98
yabai -m config normal_window_opacity        0.93
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# Boarders 
# yabai -m config window_border on
# yabai -m config window_border_width 10
# yabai -m config active_window_border_color 0xff$c4
# yabai -m config normal_window_border_color 0xff$p1

# general space settings
yabai -m config layout                       bsp
yabai -m config external_bar                 all:28:0
yabai -m config top_padding                  5   #30
yabai -m config bottom_padding               5   #30
yabai -m config left_padding                 5   #30
yabai -m config right_padding                5   #30
yabai -m config window_gap                   5   #30

# Running through float windows

# yabai -m config --space 5 layout             float
# yabai -m config --space 6 layout             float

# App rules
# yabai -m rule --add app=Alacritty space=1
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app=Dashlane manage=off
yabai -m rule --add app=Übersicht manage=off
# yabai -m rule --add app=Firefox space=2
yabai -m rule --add app="Microsoft Teams" space=3
yabai -m rule --add app="^BIG-IP" manage=off

yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=display_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-spaces-jsx\"'"
yabai -m signal --add event=space_changed action="osascript -e 'tell application \"Übersicht\" to refresh widget id \"simple-bar-processes-jsx\"'"

echo "yabai configuration loaded.."
