return {
  -- "ahmedkhalf/project.nvim",
  -- lazy = false,
  -- config = function()
  --   require("project_nvim").setup({
  --     -- your configuration comes here
  --     -- or leave it empty to use the default settings
  --     -- refer to the configuration section below
  --     patterns = { ".git", "_darcs", ".hg", ".bzr", ".svn", "Makefile", "package.json", "!>packages" },
  --     exclude_dirs = { "~/code/infrastructure-scripts/*" },
  --   })
  --   require("telescope").load_extension("projects")
  -- end,
  -- keys = {
  --   {
  --     "<leader>fm",
  --     function()
  --       require("telescope").extensions.projects.projects({})
  --     end,
  --     desc = "Find Project",
  --   },
  -- },
}
